### ISSUE TITLE
Can the NER model change from BERT+Linear_layer to BERT+CRF?

### ISSUE THREAD

**Issue by maohbao** [cliang1453/BOND#8]
Thank you very much for the work!  I have a question,

If keeping your framework unchanged, just use BERT+CRF instead of BERT+Linear_layer as the NER model, is it available? Thank you very much!

**Comment by HMJiangGatech** [comment]
CRF is not implemented in this repo. 
There are some problems you may want to know before using CRF:
1. Traditional CRF layer implementations are not designed for BERT, since they do not consider subword tokens (e.g., AllenNLP implementation). In BERT, only the first token of each word is considered when doing NER. 
2. Soft label is not applicable, as it is designed for token classification and is based on cross-entropy loss, which is different from the negative log-likelihood loss used in CRF.

**Comment by maohbao** [comment]
Hi HMJiangGatech,

Thanks for your reply!

1. Ok, I will consider the subword tokens in NER;
2. I means, use BERT+Linear_layer+CRF as the student model, keep the teacher model unchanged(BERT+Linear_layer). I know the modeling_roberta.py file should be changed accordingly, the KLDivLoss should be changed to log-likelihood loss, is it right? 

I want to know if this idea is practicable or not. Thank you very much!

**Comment by HMJiangGatech** [comment]
Yes. I think you can try both CRF teacher + CRF student and non-CRF teacher + CRF student.

**Comment by maohbao** [comment]
> Yes. I think you can try both CRF teacher + CRF student and non-CRF teacher + CRF student.

Thank you very much!

**Comment by viktor-shcherb** [comment]
@maohbao Hi! Have you had any luck adapting BOND to using CRF layer?

**Comment by maohbao** [comment]
@ViktorooReps I discontinue this project...

**Comment by viktor-shcherb** [comment]
@maohbao Was there any particular reason for discontinuation? Are there any pitfalls I should be aware of?
